# Generated by Django 4.2 on 2023-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pic')),
                ('details', models.TextField()),
            ],
        ),
    ]
